// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 角色擁有的模組權限
/// </summary>
public partial class SysProgramConfig
{
    /// <summary>
    /// 程式設定編號（主鍵）
    /// </summary>
    public int ProgramConfigId { get; set; }

    /// <summary>
    /// 模組名稱
    /// </summary>
    public string ModuleId { get; set; }

    /// <summary>
    /// 模組代號（唯一）
    /// </summary>
    public string ProgId { get; set; }

    public string ProgName { get; set; }

    public string Icon { get; set; }

    public string Area { get; set; }

    public string Controller { get; set; }

    public string ActionName { get; set; }

    /// <summary>
    /// 是否啟用（0=否，1=是）
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 顯示順序
    /// </summary>
    public int OrderSeq { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建立時間 (UTC)
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間 (UTC)
    /// </summary>
    public DateTime? RevisedDate { get; set; }
}