// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FlexBackend.Core.Models;

public partial class tHerdDBContext : DbContext
{
    public tHerdDBContext(DbContextOptions<tHerdDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SysProgramConfig> SysProgramConfigs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SysProgramConfig>(entity =>
        {
            entity.HasKey(e => e.ProgramConfigId).HasName("PK__SYS_Prog__3E6165A289EDCC42");

            entity.ToTable("SYS_ProgramConfig", tb =>
                {
                    tb.HasComment("角色擁有的模組權限");
                    tb.HasTrigger("TR_SYS_ProgramConfig_ModuleIdCheck");
                });

            entity.HasIndex(e => e.ProgId, "UQ_SYS_ProgramConfig_ProgId").IsUnique();

            entity.Property(e => e.ProgramConfigId).HasComment("程式設定編號（主鍵）");
            entity.Property(e => e.ActionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Area)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Controller)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasComment("建立時間 (UTC)");
            entity.Property(e => e.Creator).HasComment("建檔人員");
            entity.Property(e => e.Icon)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasComment("是否啟用（0=否，1=是）");
            entity.Property(e => e.ModuleId)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasComment("模組名稱");
            entity.Property(e => e.OrderSeq).HasComment("顯示順序");
            entity.Property(e => e.ProgId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("模組代號（唯一）");
            entity.Property(e => e.ProgName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.RevisedDate).HasComment("異動時間 (UTC)");
            entity.Property(e => e.Reviser).HasComment("異動人員");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}